name: build

on:
  push:
    branch:
      - master

jobs:
#  clang-format:
#    runs-on: ubuntu-20.04
#    steps:
#      - name: checkout
#        uses: actions/checkout@v2
#        with:
#          fetch-depth: 0
#      - name: clang-format
#        run: |
#          git submodule update --init --recursive
#          docker run --rm -v ${PWD}:/src wiiuenv/clang-format:13.0.0-2 -e gtitles.c -e gtitles.h -e SDL_FontCache.c -e SDL_FontCache.h -r ./src ./include
  build-binary:
    name: Build binary
    runs-on: ubuntu-20.04
#    needs: clang-format
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build artifacts
        run: |
          docker build . -t builder
          echo ${{ secrets.ENC_KEY }} > encryptKeyWith
          docker run --rm -v ${PWD}:/project builder python3 build.py
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: soh
          path: out/*
          if-no-files-found: error
